spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/csnojam?userUnicode=true&characterEncoding=utf-8
    username: javauser
    password: javauser

  jpa:
    hibernate:
      ddl-auto: update