spring:
  profiles:
    include: secrets

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
      username: sa

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        globally_quoted_identifiers: true

  jackson:
    serialization:
      write-dates-as-timestamps: false

  output:
    ansi:
      enabled: always

logging:
  level:
    root: info

